### PR TITLE
Update welcome.md

### PR DESCRIPTION
**Pull request by Noro95**

### CODE REVIEW

**Comment by Larsundso** [comment]
this code is very bad 👎👎👎👎👎👎👎👎

**Comment by Noro95** [comment]
> > this code is very bad 👎👎👎👎👎👎👎👎
> 
> fuck you

dont be sad huso

**Comment by AwesomeStickz** [comment]
> > > this code is very bad 👎👎👎👎👎👎👎👎
> 
> > fuck you
>
> dont be sad huso

stfu please, thank you

**Comment by Noro95** [comment]
can you please delete this pr :3

**Pull request merged**
